### ISSUE TITLE
Corrupted archive and incomplete files

### ISSUE THREAD

**Issue by Keiyuu** [webtor-io/player-sdk-js#58] opened 2021-12-13 20:23 UTC
I'm trying to download .mkv movie files with webtor but every single one of them ends up being corrupted.

The files are about 10-15 GB each and while the whole .zip file shows the correct size, the actual video file inside the archive is only about 4 GB. WinRAR refuses to unpack it and when I manage to unpack it with 7zip the video file is incomplete and only about a third of the whole movie.

I already tried a download manager instead of using the browser and it's still the same issue.

**Comment by vintikzzz** [comment] 2021-12-13 22:01
@Keiyuu I need torrent file or magnet url to check...

**Comment by Keiyuu** [comment] 2021-12-13 22:57
Here are some examples which were corrupted:

magnet:?xt=urn:btih:5C4F0D8628CA5A13B6DE3D9AC8BAA0C17D827F0D&tr=http%3A%2F%2Fbt.t-ru.org%2Fann%3Fmagnet&dn=%D0%A5%D1%80%D0%BE%D0%BD%D0%BE%D1%81%20%2F%20Cronos%20(%D0%93%D0%B8%D0%BB%D1%8C%D0%B5%D1%80%D0%BC%D0%BE%20%D0%94%D0%B5%D0%BB%D1%8C%20%D0%A2%D0%BE%D1%80%D0%BE%20%2F%20Guillermo%20del%20Toro)%20%5B1993%2C%20%D0%9C%D0%B5%D0%BA%D1%81%D0%B8%D0%BA%D0%B0%2C%20%D1%83%D0%B6%D0%B0%D1%81%D1%8B%2C%20%D1%82%D1%80%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%2C%20%D0%B4%D1%80%D0%B0%D0%BC%D0%B0%2C%20%D0%BA%D0%BE%D0%BC%D0%B5%D0%B4%D0%B8%D1%8F%2C%20BDRip%201080p%5D%20MVO%20Sub%20rus%20%2B%20Original%20spa

magnet:?xt=urn:btih:017F7325B75E8E28A48B06DE8D1F341B9498D4F8&tr=http%3A%2F%2Fbt2.t-ru.org%2Fann%3Fmagnet&dn=%D0%97%D0%B0%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F%20%2F%20Contracted%20(%D0%AD%D1%80%D0%B8%D0%BA%20%D0%98%D0%BD%D0%B3%D0%BB%D1%8D%D0%BD%D0%B4%20%2F%20Eric%20England)%20%5B2013%2C%20%D0%A1%D0%A8%D0%90%2C%20%D1%83%D0%B6%D0%B0%D1%81%D1%8B%2C%20%D1%82%D1%80%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%2C%20%D0%B4%D1%80%D0%B0%D0%BC%D0%B0%2C%20BDRemux%201080p%5D%20VO%20%2B%20Original%20(Eng)%20%2B%20Sub%20(Eng)

**Comment by ghost** [comment] 2021-12-14 16:18
Same issue here, I have been trying to download Cowboy Bebop season 1 as a .zip file and extract it, but it says "An error occured while loading the archive" on Linux Mint... and so does RAR and FX File Explorer.
Links to files:
18.4 GB
`https://solidtorrents.net/torrents/cowboy-bebop-s01-1080p-nf-web-dl-ddp5-1-h-264-enia-dedf6/6197b99070367639874c0a68/`
7.73 GB
`https://solidtorrents.net/torrents/cowboy-bebop-s01-1080p-webrip-x265-rarbg-43edd/6198cc047036763987538532/#`

I have downloaded Bo Burnham꞉ Inside (2021) like 4 days ago and it worked fine.

**Comment by vintikzzz** [comment] 2021-12-14 16:39
Downloaded archives are not corrupted, but it has some special «feature». It has no CRC32 sums to validate its integrity because it’s created on the fly from BitTorrent network and there is no way to generate CRC32 sum beforehand.
WinRAR is good archiver, but I would suggest to use 7-Zip. It also shows CRC32 errors, but without interrupting unpacking process. I will check your examples to be sure is there any other issue or not...

**Comment by ghost** [comment] 2021-12-14 18:35
Tried 7 zip and it gives me CRC failed error.

**Comment by vintikzzz** [comment] 2021-12-14 18:38
7-Zip also shows this error as I mentioned before, but this doesn't mean that we have actually an error, it only means that the archive doesn't have CRC32 sums to check.

**Comment by ghost** [comment] 2021-12-14 18:40
Yeah but it does not extract the files

**Comment by ghost** [comment] 2021-12-14 18:45
However when I download one episode as a mp4 file than every episodes in zip file then it works fine. I think the problem is that when I lose internet connection for example 10 seconds, download manager will retry until internet connection will be present again and... perhaps... somehow it might get corrupted by that?

**Comment by vintikzzz** [comment] 2021-12-14 18:57
Reasonable assumption. I tried downloads only with Chrome and no issues so far. Also I did test with broken connection/ resuming and so on... What kind of download manager do you use?

**Comment by ghost** [comment] 2021-12-14 19:00
1DM+
`https://play.google.com/store/apps/details?id=idm.internet.download.manager.plus&hl=en&gl=us`

**Comment by ghost** [comment] 2021-12-14 19:30
Weird that it shows archives as corrupted since I have been downloading other files from Your site for like a month and it worked fine. Anyway, I'm going to try download Cowboy Bebop - The Series (1998-99) from this torrent `https://1337x.to/torrent/4595635/SHINICHIRO-WATANABE-Anime-1994-2019-COMPLETE-Cowboy-Bebop-SERIES-and-Knockin-on-Heaven-s-Door-Movie-Samurai-Champloo-Kids-on-the-Slope-plus-2018-Film-Space-Dandy-Terror-in-Resonance-Carole-Tuesday-Michiko-and-Hatchin-Lupin-the-Third-The/` as a zip file and some episodes as a .mkv file and tomorrow I will comment the results here

**Comment by vintikzzz** [comment] 2021-12-14 20:32
ok, I am currently downloading one of your examples. I will check it as soon as it downloads.

**Comment by vintikzzz** [comment] 2021-12-14 21:07
I have checked this one
`https://solidtorrents.net/torrents/cowboy-bebop-s01-1080p-nf-web-dl-ddp5-1-h-264-enia-dedf6/6197b99070367639874c0a68/`
All files were unpacked and I was able to play them. Can you reproduce on another device?

**Comment by Keiyuu** [comment] 2021-12-15 03:31
So I've downloaded another file and having the same issue again...

You can see the size of the archive is correct, around 12 GB:
![image](https://user-images.githubusercontent.com/19988276/146116997-f274c2aa-025f-4d86-b212-110f9afdaeec.png)

But here is what 7zip shows:
![image](https://user-images.githubusercontent.com/19988276/146117126-8e048c88-e96a-49ef-a3ad-d45e44e19c83.png)

When I unpack it, the .mkv file is exactly 3,99 GB, or 4.294.967.295 Bytes (as you can see in the screenshot).

And this is the case with every large movie file I download. The file inside the archive always caps out at exactly 4.294.967.295 Bytes (4 GB), resulting in incomplete files.


Here's the magnet link for reference:
`magnet:?xt=urn:btih:AC616EAC33B2068230FA1E37D9DC63B238743DAB&tr=http%3A%2F%2Fbt2.t-ru.org%2Fann%3Fmagnet&dn=%D0%9F%D0%BE%D0%B1%D0%BE%D1%87%D0%BD%D1%8B%D0%B9%20%D1%8D%D1%84%D1%84%D0%B5%D0%BA%D1%82%20%2F%20Side%20Effects%20(%D0%A1%D1%82%D0%B8%D0%B2%D0%B5%D0%BD%20%D0%A1%D0%BE%D0%B4%D0%B5%D1%80%D0%B1%D0%B5%D1%80%D0%B3%20%2F%20Steven%20Soderbergh)%20%5B2013%2C%20%D0%A1%D0%A8%D0%90%2C%20%D1%82%D1%80%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%2C%20%D0%B4%D1%80%D0%B0%D0%BC%D0%B0%2C%20%D0%BA%D1%80%D0%B8%D0%BC%D0%B8%D0%BD%D0%B0%D0%BB%2C%20BDRip%201080p%5D%20Dub%20(R5)%20%2B%20Original%20(Eng)%20%2B%20S`

**Comment by vintikzzz** [comment] 2021-12-15 15:16
Oh no... I have reproduced it. I notify you when it will be fixed! Thanks!

**Comment by vintikzzz** [comment] 2021-12-17 21:31
Fixed there https://github.com/webtor-io/torrent-archiver/commit/21a5e83eb80de5c12bb77f09db2d7f0869e6d877
May I ask you to check?

**Comment by Keiyuu** [comment] 2021-12-18 23:20
It works now, thanks a lot! 😄

**Closed as completed** 2021-12-19 10:33 UTC
